
language: python

sudo: false
dist: trusty


cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache
  - $HOME/.pip-cache

matrix:
  include:
    - python: '3.6'
      env: TOXENV="py36-linux"

install:
  - pip install -r requirements.txt
  - pip install tox
  - python -m nltk.downloader popular

script: tox -vv
