language: python

sudo: false

python:
  - "3.6.2"

install:
  - pip install .[test]

script:
  - py.test --cov=timefhuman tests timefhuman

after_success:
  - CI=true TRAVIS=true coveralls
