language: python

install:
  - pip install -r docs/sphinx-requirements.txt
  - pip install codecov
  - pip install tox

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=qa

script:
  - tox
  
branches:
  only:
  - master
  - dev

after_success:
  - codecov
