language: python
dist: xenial

# sudo false implies containerized builds
sudo: false

notifications:
    email: false

python:
  - 3.5
  - 3.6
  - 3.7

cache:
    directories:
    - $HOME/env

before_install:
    - bash .travis_dependencies.sh
    - export PATH="$HOME/env/miniconda$TRAVIS_PYTHON_VERSION/bin:$PATH";
    - hash -r
    - source activate test-environment

install:
    - pip install -e .[docs,tests]

script:
    - pytest

after_success:
    - coveralls
