language: python
python:
  - "3.6"
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - pip install codecov
# command to run tests
script: 
    nosetests --with-coverage
after_success:
    codecov -t 2f80a858-5d08-47f6-8dbd-b689c49d0952
