language: python
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install: 
  - "pip install ."
  - "pip install pytest-cov"
  - "pip install codecov"
# command to run tests
script: py.test --cov=./
# codecov
