
sudo: false
language: python
python:
  - 3.6
cache: pip
install:
  - easy_install distribute
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest --cov=adnc test

