dist: xenial

language: python

notifications:
    email: false

python:
    - "2.7"
    - "3.5"
    - "3.6"

before_install:
    - pip install python-coveralls
    - pip install "pytest-faulthandler>=1.5.0,<2.0.0"
    - pip install pytest-cov
    - sudo add-apt-repository -y ppa:mc3man/xerus-media
    - sudo apt-get update
    - sudo apt-get install -y ffmpeg
    - ffmpeg -hwaccels

install:
    - pip install "tensorflow>=1.12.0,<1.14.0"
    - pip install pytest
    - pip install -e .[tests]

#before_script:
#    - pep8 tests

script:
#    - nosetests -v --with-coverage --cover-package=mir_eval
#    - python setup.py build_sphinx
#    - python setup.py egg_info -b.dev sdist --formats gztar
     - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
     - py.test
     - kill %1

after_success:
    - coveralls
