dist: xenial
os: linux
language: python

python:
  - 3.6
  - 3.7
  - 3.8

cache: apt

addons:
  apt:
    packages:
    - liblapack-dev

services:
  - xvfb

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda create --yes --name testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv

install: pip install -e ".[dev]" codecov

script: pytest --cov prince

after_success: codecov
