dist: xenial
language: python
python:
  - "3.7"
branches:
  only:
    - master
install:
  - python3 -m pip install --upgrade --force-reinstall --no-cache-dir --editable=".[cpu,dev]"
  - python3 -m pip install --no-cache-dir "cloudpickle==1.3.0"
script:
  - flake8
  - travis_wait pytest
  - cd guide && bash .run_notebooks.sh
