dist: xenial
language: python
python:
  - 3.7
install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install
script:
  - poetry run ./update.py
env:
  global:
    secure: OOsu31K3CqqGx0dx/ka5/+FCRdAXAgMk/NyiF7jAJUnsHw8DY3P1RGjvrNkAO+exiQsIiflF9LF58F3AhvPi2pU7op+BE+mF1ZEcMhv0xSn9R72tNHN03YVRuaZHV8ANr4JQtE3H6DGU2HgPn1T0BDH+CWkfhDvvEnXSrxA4huIO9bdVhrHL7FVJ/Q14NM/oa+smLU+ts8u2xh/Bxr6RW7UPKpgh1q5oWqo4pw9B71wLO/4cMvlIQ5r2qA5X9GT7b8HdBKSRekJgmGpHoPu23CnVN9OK1fcMavL1CeRYQDG96O4vtb6hEX/pvq2u32yh3JQPIruOKwN//5OEkV34OT2AkYv9FJ8VHuhYE+greKMgrfuH3pSF9E2yydGETe2bgRvzyQtTMfDnnQn4hVfwSs0GkP+6C6uPkhVdgujs8eLlD3pyXciRwDkS8yBAmktv0jBWa8dESiO559TfWXO9VLM8oh+yzYuFroSha2fQvtu85bTPm9PF86Qfjl8c2c0g0PGewGNzG2pUtXLrOSJCKzWbx8Uz04UKrk1Dq0Gc86OJidPJ574Be5iCe5Fua5qo8BpEVn1b+OMa8fJMrQ1h50VKfx3Yz1SWksrDHdxEYFYK1JIOezQqmxt479T8XSBJZLNTFlz+4G++KeKNSvkiJLPz0UJ7acAMref3Ow02RZc=
