sudo: false
cache: pip
language: python
python:
  - 3.7
stages:
  - lint
  - docs
  - test
matrix:
  include:
    # lint stage
    - stage: lint
      env: TOXENV=manifest
    - env: TOXENV=pyroma
    # docs stage
    - stage: docs
      env: TOXENV=doc8
    - env: TOXENV=readme
    - env: TOXENV=docs
    # test stage
    - stage: test
      env: TOXENV=py

  allow_failures:
    - env: TOXENV=xenon
    - env: TOXENV=flake8

install:
- pip install --upgrade pip
- pip install tox codecov coverage
script:
- tox
after_success:
- tox -e coverage-report
- codecov
