language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - sudo apt-get update

  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - source activate test-environment
  - conda install -c conda-forge pywavelets
  - conda list
  - pip freeze
  - python setup.py install --user

script:
  - py.test --cov-report term-missing --cov=dictlearn tests/
