# whitelist
branches:
    only:
        - master
notifications:
  irc:
    channels:
      - "irc.uvt.nl#gitlama"
    template:
      - "%{repository_slug}#%{build_number} %{message} --> %{build_url}"
    skip_join: true
language: python
dist: trusty
python:
    - "2.7"
    - "3.4"
    - "3.5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y xmldiff
  - pip install -U setuptools
install:
    - pip install -r requirements.txt
    - python setup.py install
script:
    - bash pynlpl/tests/test.sh
