language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.6-dev'
- '3.7-dev'
install:
- pip install -r requirements/test.txt
script:
- python -m pytest --cov=chatette tests/
after_script:
- cd ~
after_success:
- codecov
