language: python
python:
    - 3.6

sudo: false

# Pre-install packages for the ubuntu distribution
cache:
    apt: true
    directories:
        - $HOME/.cache/pip

addons:
    apt:
        packages:
            - libblas-dev
            - liblapack-dev
            - libatlas3gf-base
            - libatlas-dev

# command to install dependencies
install:
    - pip install -U pip wheel
    - pip install --install-option="--no-cython-compile" cython
    - pip install -r requirements.txt
    - python setup.py develop

# command to run tests
script:
    - black --check inverse_covariance
    - black --check examples
    - python -m pytest --showlocals --pyargs
