language: python

cache: pip

jobs:
  include:
    - os: linux
      python: 3.5
      env: TOXENV=py35

    - os: linux
      python: 3.6
      env: TOXENV=py36

    - os: linux
      python: 3.7
      env: TOXENV=py37

    - os: linux
      python: 3.8
      env: TOXENV=py38

    - os: linux
      python: 3.9-dev
      env: TOXENV=py39

    - os: linux
      python: pypy3
      env: TOXENV=pypy3

    - os: linux
      python: 3.7
      env: TOXENV=cov
      after_success:
        - travis_retry pip install coveralls
        - coveralls

    - os: osx
      language: generic
      env: TOXENV=py37

  allow_failures:
    - os: linux
      python: 3.5
      env: TOXENV=py35

    - os: linux
      python: 3.9-dev
      env: TOXENV=py39

install:
  - travis_retry bash -x .travis/install.sh

script:
  - tox

notifications:
  slack:
    secure: JTq9Gq60gZj1krX7zNNaHTUGaFhhw/gahi6OBi3aJGKrg1gxk6L+XcBu+0hKrwCUVlzAXoapkzhDSWILSR2eSq+GDzpLY0g/CZWq2jVLjnTh8YtiShYU4TiQcTOh3vVncvCKvyw+GI/CgVcvYPTFNgdH9LX09r8MEXfJmjZ5mU1mgdPRWZ2UW9C5dK7P5th+pAK0SF+MNrAaF/3/kzNO49PGZsYkTnVcKiaKdTO6YJ3JAHS9L+XLuLhAbqjAkv4gErB3OkezpEo4gwaepwtvGZfsmLQzCcagbmav3Qifnv/7XklJymXIbQ4cC10sbYCstQmXV8AkGm354I0CX1wG21PHRE0T4jtxsxbZ8nAUZ9MDW64G7bLvEYa7Kabg3e64oLfvRBLY+vQdm7km/kmdyC6Wx47xH5vtZtkC9ORILNmaI3OtKw6eyTK0s3vV/DW0IBz1ENHJWO1zZceSpujNpju9Nwgvtt3r9GpcZziq3IoRPfo/FOdwXeTO1Loh8ExpQZoRdPXFGGXd0lp/8FyE1+g2in5gl6BRau8vGiWQLWWiKMG8Hgine+fSuhkQd6b38yqbC1dpIc2td5sdgtz7ovB3PErk5CRFfq2UGZWbcfACosRaMEKAhbg8fvutWgCFloLnF/gA4cYB0uXVIfsFzGqNDAyPVo0OEKbxB+VFkjM=
