# .travis.yml needs to be present on all active branches
# check if .travis.yml is valid: http://lint.travis-ci.org/
# to skip build for given commit put [ci skip] or [skip ci] in commit message

# required for Python >= 3.7
dist: xenial

language: python

# versions supported by scikit-learn and some additional versions
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

# safelist
branches:
  only:
  - master
  - dev
  - py2

install:
  - pip install numpy
  - pip install scipy
  - pip install pandas
  - pip install scikit-learn
  - pip install nose
  - pip install coverage
  - pip install coveralls
  - pip install .

script:
  - nosetests --with-coverage --cover-package=vecstack

after_success:
  - coverage report -m
  - coveralls
