language: python
python:
  - "2.7"
  - "3.6"
  
# command to install dependencies
install: 
  - pip install -r requirements.txt  # install dependencies
  - git clone https://github.com/vkuznet/MLaaS4HEP
  - python setup.py install

# command to run tests
script: 
  - python setup.py test
