# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.6

install:
   - pip install -r requirements_dev.txt
   - pip install -e .
   - python setup.py install

script:
   - python setup.py test
   - pylint circuitpython_kernel/board.py circuitpython_kernel/kernel.py
