language: python

python:
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - export PYTHONPATH="/home/travis/WMD-group/SMACT/smact:$PYTHONPATH"

script: 
  - python3 -m smact.tests.__init__ -v
